[package]
name    = "dante"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dante"
test = false
bench = false

[dependencies]
fdt = { version = "0.1.5", features = ["pretty-printing"] }
linked_list_allocator = "0.10.5"
spinning_top = "0.3.0"
