[package]
name    = "dante"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dante"
test = false
bench = false

[dependencies]
riscv-rt = { version = "0.12", features = ["single-hart", "s-mode"] }
